language: "node_js"
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
# before_script:
#   - "npm install -g gulp-cli"
script:
  - "npm run lint"
notifications:
  email:
    on_success: never
    on_failure: never
